name: Run JavaScript script

on:
  schedule:
    - cron: '0 2 * * 0,1,5'  # Runs at 02:00 UTC on Sunday, Monday, and Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "TRACK_ID=${{ secrets.TRACK_ID }}" >> $GITHUB_ENV
          echo "BUSINESS_IDS=$(echo "${{ secrets.BUSINESS_IDS }}" | sed 's/,/;/g')" >> $GITHUB_ENV
          echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "API_KEY=${API_KEY}"
          echo "TRACK_ID=${TRACK_ID}"
          echo "BUSINESS_IDS=${BUSINESS_IDS}"
          echo "FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}"
        shell: bash

      - name: Run script
        run: npm start
