name: Run JavaScript script

on:
  schedule:
    - cron: '0 2 * * 0,1,5'
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ vars.API_KEY }}
      TRACK_ID: ${{ vars.TRACK_ID }}
      BUSINESS_IDS: ${{ vars.BUSINESS_IDS }}
      FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ vars.FIREBASE_MEASUREMENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: |
          echo "API_KEY=${{ env.API_KEY }}"
          echo "TRACK_ID=${{ env.TRACK_ID }}"
          echo "BUSINESS_IDS=${{ env.BUSINESS_IDS }}"
          echo "FIREBASE_DATABASE_URL=${{ env.FIREBASE_DATABASE_URL }}"

      - name: Run script
        run: npm start